### ISSUE TITLE
Can I use this library to decode a raw h264 stream?

### ISSUE THREAD

**Issue by fearchannel** [tanersener/mobile-ffmpeg#111]
And how?

**Comment by tanersener** [comment]
This library is capable of doing everything [ffmpeg](https://ffmpeg.org/) can do on Android and IOS platforms. So the answer is yes. But you should ask this question to [ffmpeg-user mailing list](https://ffmpeg.org/mailman/listinfo/ffmpeg-user). This is `ffmpeg` question rather than a `mobile-ffmpeg` question.
