### ISSUE TITLE
How to cancel?

### ISSUE THREAD

**Issue by fayte0618** [tanersener/mobile-ffmpeg#15]
For example you're in the middle of encoding, how do you cancel the process?

From what I understand you use shutdown? If it is, my concern is the API is not present in the IOS version. How do I cancel?

Thanks :)

**Comment by tanersener** [comment]
Well, actually I don't cancel an ongoing operation. execute() operations were designed to be blocking calls because of the ffmpeg integration and I always respected this design.

I understand why you need it but I must dig into ffmpeg sources to tell you if it is possible or not. 

Until I figure it out, I recommend creating a dedicated thread for execute() operation and cancel the thread itself. It won't stop the processing but at least you can free your resources.

**Comment by tanersener** [comment]
Added a cancel operation in [FFmpeg Android API @ dev-v2.x](https://github.com/tanersener/mobile-ffmpeg/blob/dev-v2.x/android/app/src/main/java/com/arthenica/mobileffmpeg/FFmpeg.java). IOS version will be ready later today. 

It will be included in v2.1, which I'm planning to release in a few days.

**Comment by tanersener** [comment]
Implemented in `v2.1`.

**Comment by VivekThummar52** [comment]
can i cancel specific execution like by using `id` or anything else?
