### ISSUE TITLE
How to enable 'ALSA'  to capture audio

### ISSUE THREAD

**Issue by PhachayawatAmivoice** [tanersener/mobile-ffmpeg#153]
i want to use "ffmpeg -f alsa -i hw:0 alsaout.wav"
how can i change config

please help, Thanks

**Comment by tanersener** [comment]
Unfortunately `alsa` input device is not available on both platforms.

**Comment by matteocontrini** [comment]
Is it technically possible to add support for it?

**Comment by tanersener** [comment]
Well, `alsa` needs `libasound`, so `libasound` library should be built first. Technically it should be possible but I haven't tried it before.

The biggest question for me is, do we need to support `alsa`? We already have `android_camera` device on Android and `AVFoundation` device on iOS to record audio/video. What will we gain by supporting `alsa`? Do you have a specific use case?

**Comment by matteocontrini** [comment]
I was looking into a way to record audio from a USB microphone/input card on Android (not a phone but a development board), and since the device is listed as an ALSA device I thought about ffmpeg. I then found the `AudioRecord` Android class which allows to select a device for the recording, so that seems to be a solution. Thanks for the reply!

**Comment by tanersener** [comment]
Thanks for your explanation. I think you have a valid case here. 

I expect you to be able to record audio using `android_camera` device but a test is needed for that. Can you try to record audio using `mobile-ffmpeg` and `android_camera` device?

**Comment by matteocontrini** [comment]
Ah I see what you meant. Unfortunately the device is on Android 6 so if I understand correctly camera access it not available there

**Comment by tanersener** [comment]
You are right, it's not available under API Level 24. Let me try and see if I can build `alsa` on `Android`.

**Comment by tanersener** [comment]
Unfortunately, it is not possible to build `alsa` on `Android`. `alsa` library (libasound) depends on several semaphore (`sem.h`) and shared memory (`shm.h`) functions which were introduced in API Level 26. So compilations fail under API Levels below 26. 

Since increasing API Level to 26 is not an option, `android_camera` will remain as the only option to record audio/video on `Android`.

**Comment by matteocontrini** [comment]
I see, thank you very much for investigating!
