### ISSUE TITLE
添加外部库失败

### ISSUE THREAD

**Issue by SnailLife** [tanersener/mobile-ffmpeg#275]
mac
xcode
ios

config.status：创建src / fcstdint.h：_FONTCONFIG_SRC_FCSTDINT_H
CDPATH =“ $ {ZSH_VERSION +。}：” && cd。&& / bin / sh / Users / yangxiao / Desktop / Third / mobile-ffmpeg / src / fontconfig / missing aclocal-1.16 -I m4
/ Users / yangxiao / Desktop / Third / mobile-ffmpeg / src / fontconfig / missing：第81行：aclocal-1.16：找不到命令
警告：您的系统上缺少'aclocal-1.16'。
仅当您修改了“ config.ac”
包含的“ acinclude.m4”或“ configure.ac”或m4文件时，才需要使用它。
“ aclocal”程序是GNU Automake软件包的一部分：
https : //www.gnu.org/software/automake
它还需要GNU Autoconf，GNU m4和Perl才能运行：
https : //www.gnu.org / software / autoconf
https：
https://www.perl.org/
make：*** [aclocal.m4]错误127

**Comment by tanersener** [comment]
See [Reconf Option](https://github.com/tanersener/mobile-ffmpeg/wiki/Reconf-Option).

**Comment by todother** [comment]
哥们你怎么下下来的。。我用了各种方法也没成功下载。。

**Comment by tanersener** [comment]
@todother 你有同样的错误吗, 您可以共享日志吗？

**Comment by todother** [comment]
> @todother 你有同样的错误吗, 您可以共享日志吗？

Hi @tanersener , I've another issue. 
Don't know why, Git always reject the download request for MobileFFMpeg from curl or pod install even download the zip file in manual-installation release page.

I've tried for a few days for downloading but...still failed. Maybe it's due to some policy by Chinese internet principle. 

BTW, REALLY GOOD JOB!

**Comment by tanersener** [comment]
> Don't know why, Git always reject the download request for MobileFFMpeg from curl or pod install even download the zip file in manual-installation release page.

They are all github.com links. There might be a restriction about downloading files from github.com.
