### ISSUE TITLE
-report option not working

### ISSUE THREAD

**Issue by JayParikh20** [tanersener/mobile-ffmpeg#302]
Built library using ./android.sh --enable-gpl --enable-x264 --lts

Sample command
`"-y -i " + srcMp4Path + " -vf select=eq(pict_type\\,PICT_TYPE_I) -report -loglevel debug -vsync 2 -f image2 "+ outMp4Path`
output should be in thumbnails-%02d.jpeg format

Environment variable set using "setNativeEnvironmentVariable" function in Config file
FFREPORT=file=/storage/emulated/0/test/fflog.txt:level=48

Expected Behavior
Report option should print complete log in detail, for eg PICT_TYPE of each frame.

Current Behavior
It is saving the file in the given FFREPORT location, but log has only the command line printed.

> Command line: -y -i .... etc thats it!

Environment
Platform: Kali Linux for Android
Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64]
FFmpeg Source brach: 4.3-dev
Android NDK version: R20b

**Comment by tanersener** [comment]
Thank you for reporting this issue. 

`mobile-ffmpeg` replaces `log_callback_report` function with `mobileffmpeg_log_callback_function` to implement `LogCallback` functionality of the library. Unfortunately this change breaks the behaviour of `-report` option. Because `-report` option uses `log_callback_report` to write output to a file.

**Comment by tanersener** [comment]
fixed in `development` branch

**Comment by tanersener** [comment]
Fixed in `v4.3.1` release.

**Comment by JayParikh20** [comment]
Thank you so much!
