### ISSUE TITLE
IOS - Read-only file system

### ISSUE THREAD

**Issue by Yosifz8** [tanersener/mobile-ffmpeg#309]
**Description**
I want to convert m3u8 stream to mp4 file with FFMPEG with this code:
```
    [MobileFFmpeg execute: @"-i http://1107942067.rsc.cdn77.org/UpFiles/2020/1/4/42/138804/720p.m3u8 -c copy -bsf:a aac_adtstoasc output.mp4"];
    
    int rc = [MobileFFmpeg getLastReturnCode];
    NSString *output = [MobileFFmpeg getLastCommandOutput];

    if (rc == RETURN_CODE_SUCCESS) {
        NSLog(@"Command execution completed successfully.\n");
    } else if (rc == RETURN_CODE_CANCEL) {
        NSLog(@"Command execution cancelled by user.\n");
    } else {
        NSLog(@"Command execution failed with rc=%d and output=%@.\n", rc, output);
    }
    
    [MobileFFmpeg cancel];
```

**Expected behavior**
I want to convert the m3u8 to mp4 file

**Current behavior**
Get this error:
`ERROR: output.mp4: Read-only file system`

**Logs**
https://ghostbin.co/paste/v2eq4

**Environment**
 - Platform: IOS
 - Xcode version: 11.3

**Comment by tanersener** [comment]
Can you please use full path of your file? 
You can save your file to your document directory if you don't know where to save it.

**Comment by DijonLee** [comment]
having this same problem



    func convertVideo(myFile:String){
    var command = "ffmpeg -i " + myFile + " LostInTranslation.mp4"
               var rc = MobileFFmpeg.execute(command)
                 if (rc == RETURN_CODE_SUCCESS) {
                   print("Command execution completed successfully.\n");
                   } else if (rc == RETURN_CODE_CANCEL) {
                   print("Command execution cancelled by user.\n");
                   } else {
                   print("Command execution failed with rc=%d and output=%@.\n", rc, MobileFFmpegConfig.getLastCommandOutput);
                    print(MobileFFmpegConfig.getLastReturnCode())
                    print(MobileFFmpegConfig.getLastCommandOutput())
        }


My File path doesnt seem to be the issue since I tested using my regular ffmpeg command and that seemed to work. Testing on iphone simulator also gives the same result as below.


` 2020-05-07 16:21:27.463489-0400 WebmBrowser[8382:1386648] Loaded mobile-ffmpeg-full-gpl-arm64-4.3.2-20200415`

`2020-05-07 16:21:27.475964-0400 WebmBrowser[8382:1387428] ERROR: /var/mobile/Containers/Data/Application/8D4E054A-1AD8-4EBB-B619-5D5E374308A3/Documents/Volcano_Lava_Sample.webm: Invalid data found when processing input
Command execution failed with rc=%d and output=%@.`
