### ISSUE TITLE
How to get media file information like bitrate using these so files ?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#33]
I just tried to run FFMPEG.execute("-i "+file_path), error happened as below.

10-04 10:17:04.682: I/mobile-ffmpeg(805): -i /storage/emulated/0/DCIM/1505634754324_new_new_1.mp4
10-04 10:17:04.683: I/mobile-ffmpeg(805): Command execution failed with rc=1.

Thanks.

**Comment by tanersener** [comment]
`ffmpeg` itself does not have a special command to get file information, but when a file is provided as an input (with `-i` flag), it prints file information of that input file to the configured log output. 

Additionally, according to `ffmpeg` command rules each command must specify at least one output file, therefore running `ffmpeg -i <path>` terminates with `rc=1`, because there is not any output files specified. Also command output displays an error message, `At least one output file must be specified` telling why it has terminated with `rc=1`.

You are not doing anything wrong, you just need to look into command output. It will have a similar output as below:

```
[theora @ 0x7f2f5bbe9100] 
    7 bits left in packet 82
    [ogg @ 0x7f2f5984ce00] 
Broken file, keyframe not correctly marked.
    Input #0, ogg, from 'https://download.blender.org/peach/trailer/trailer_400p.ogg':
      Duration: 
    00:00:33.00
    , start: 
    0.000000
    , bitrate: 
1057 kb/s
        Stream #0:0
    : Video: theora, yuv420p(bt470bg/bt470bg/bt709), 720x400
    , 
    25 fps, 
    25 tbr, 
    25 tbn, 
    25 tbc
    Metadata:
          ENCODER         : 
    ffmpeg2theora 0.19
        Stream #0:1
: Audio: vorbis, 48000 Hz, stereo, fltp, 80 kb/s
        Metadata:
          ENCODER         : 
ffmpeg2theora 0.19
    At least one output file must be specified
```

**Comment by suncj518** [comment]
Thanks for your clear answer.
