### ISSUE TITLE
How to compile the terminal binary for ios?

### ISSUE THREAD

**Issue by stemac93** [tanersener/mobile-ffmpeg#333]
Hi, I would to use ffmpeg through terminal on a jailbroken device.

**Comment by tanersener** [comment]
`MobileFFmpeg` build scripts do not create `ffmpeg`/`ffprobe` binaries. They generate `ffmpeg` static libraries by default.

There exists a [Building ffmpeg executable on Android](https://github.com/tanersener/mobile-ffmpeg/wiki/Building-ffmpeg-executable-on-Android) guide written to help users who want to use `ffmpeg` executable on Android. You can follow the steps listed in that guide and try to generate binaries for iOS. However, I don't know if that will work because generating executables on `iOS` is not a feature I want to support.
