### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by ayon115** [tanersener/mobile-ffmpeg#37]
I am sorry if my question is irrelevant. I have read a lot threads about against using FFMpeg in commercial iOS app in Appstore due to LGPL/GPL license. I read the list of things to do to comply. Sorry again for asking this, my question is, can I use this mobile-ffmpeg library to my iOS & android app safely for iOS Appstore & Google play ?

**Comment by tanersener** [comment]
There are multiple binaries produced by the library. It depends on the version you use.

First of all, I must remind that all binaries except `IOS universal static binaries` (libraries with `-ios-static-universal` postfix) are `dynamically linked`.

- `Dynamically linked LGPL libraries` can be safely used in a commercial application. Your application will have its own license and `mobile-ffmpeg` will be licensed under `LGPL`. Dynamic linking allows that.

- When `Statically linked LGPL libraries` are used, your application will be licensed under `LGPL`. So you must meet all conditions defined by `LGPL`. This means `you must provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application`. It is hard to provide an application in an object format to allow relinking, so most of the users prefer providing source code of their application.

- If `GPL libraries` are used, either dynamically or statically linked, your application will be licensed under `GPL`, all conditions defined by `GPL` must be met. You must `make the source code available to the users of your application as described in the GPL, and they must be allowed to redistribute and modify it as described in the GPL`.
