### ISSUE TITLE
about subtitles 

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#38]
@tanersener 
I found the subtitles usage below in test app.
"-y -i %s -vf subtitles=%s:force_style='FontName=MyFontName' -c:v mpeg4 %s"

Question 1:
May I know where I need to put the MyFontName file in Android eclipse project?   In asset directory?

Question 2:
Can I use absolute path ( like '/sdcard/font.ttf') in MyFontName  above to run ffmpeg command?

Thanks.

**Comment by tanersener** [comment]
Hi,

**Q1:** In Android you can't use resources directly, you need to save them as files before using them. `rawResourceToFile()` method inside [MainActivity.java](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/test-app/src/main/java/com/arthenica/mobileffmpeg/test/MainActivity.java) of `test-app` does that. You can use it in your application.

**Q2:** I didn't test it, so I'm not % 100 sure, but as far as I know you can't include path in font name. You can see how a font is registered inside `registerAppFont()` method inside [MainActivity.java](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/test-app/src/main/java/com/arthenica/mobileffmpeg/test/MainActivity.java) of `test-app`. You can put your font wherever you want, but then you need to register parent directory with `Config.setFontDirectory` method in order to use that font.
