### ISSUE TITLE
Missing iOS-static-universal builds for 4.3.2

### ISSUE THREAD

**Issue by cyliax** [tanersener/mobile-ffmpeg#383]
Hey, thanks for your great work. For Unity it is necessary to work with these static universal iOS packages. Can you provide them as well or how would it work with the new xcframework files?

**Comment by tanersener** [comment]
In order to support the new `x86_64 (Mac Catalyst)` architecture I had to use the new `xcframework` format for this release. Because it is not possible to use the old framework format and universal libraries to ship `x86_64 (Mac Catalyst)`. Technically, you can still build them using the scripts. But they will not include `x86_64 (Mac Catalyst)` inside.

I know that iOS universal binaries are still necessary. So I decided to use the new `xcframework` format only on `Main` iOS releases like `4.3.2`. `LTS` iOS releases will still be published using the  old `framework` format and static universal binaries.

**Comment by cyliax** [comment]
Okay, thank you very much. So I will wait for the updated LTS version 4.3.2. I was just curious why it looks different this time.
