### ISSUE TITLE
Provide an API method to change the working directory

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#434]
Default working directory on both platforms is `/`. Unfortunately, this directory path is not writable and users complain a lot about permission errors when do not use full system paths. 

Also on some cases, like #432, where an external library does not allow overriding the default input/output file path, it is not possible to access those files.

Providing an API method to change the working directory can overcome all these problems.

**Comment by alexcohn** [comment]
There are two approaches for such API. 

The minimalistic one would allow the user to change the working directory for the app process, and then the paths to files specified on the pseudo command-line will automatically use this directory as base. Actually, there is no need in a new API method to achieve this: on iOS, call `chdir()`. On Android, call to `chdir()` must be wrapped in a JNI function. The problem is that this affects everything that happens in the app, and if at any point any other component (the app itself, or a library that the app uses) changes the working directory again, without *informing* **mobile-ffmpeg**, this will still take precedence. And vice versa, who knows what other parts of the app will misbehave when the current directory changes.

A more sophisticated approach would set a working directory specific to mobile-ffmpeg, so that the file protocol will use this directory for all file paths that are not absolute, but keep the system-defined working directory untouched.

**Comment by tanersener** [comment]
Setting a working directory specific for `mobile-ffmpeg` means updating all files that actually opens a file. And this is a big change. For example, there are 45 files which use `fopen` in `development` branch right now. There are other methods like `avio_open`, `av_fopen_utf8` and `ff_load_image` that has to be updated as well. This is a very expensive solution for such a small feature. Also, it won't be easy to maintain it.

I plan to add this function but I'm not sure whether to automatically call this API method and change the working directory. Because, I don't want to do something that will effect other parts of the application. It creates an unnecessary complexity in my opinion. I think setting working directory at the beginning of `execute` and reverting back to the previous working directory at the end can be an option. But still not a nice solution. It still has side effects.

**Comment by alexcohn** [comment]
Yes, the dilemma is clear. The change could be manageable only if the `open()` and `opendir()` system calls can be replaced with patched ones. There are a lot of `fopen()` calls in **libavfilter**, and maybe a separate patch would be better for them.

Note that `avio_open` and her kin only pass the control to the relevant protocol, and don't require changes at all. 

Setting working directory at the beginning of `execute` is a dangerous approach. For one, it will effect the other threads of the current app. But also, if async ffmpeg executes are run in parallel, then restore after the first may change the context of the second.

**Comment by tanersener** [comment]
I agree. There must be a better way to do this.
