### ISSUE TITLE
Download external library sources as zip packages

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#459]
`development` branch introduces a new mechanism to clone repositories of external library sources. Newly added `clone_git_repository` function in `arch-common.sh` file downloads the source code of an external library using a commit id. However, the function is not optimised, runs multiple `git` commands and has some manual steps as well. 

It would be nice to achieve the same thing by downloading a zip package containing the source code for that particular commit.

**Comment by alexcohn** [comment]
Using zip packages (e.g. https://github.com/cisco/openh264/archive/a60e28efe227ea8ea760b1e29a8943e371ebe4b3.zip) does not help reduce the disk size compared to `git clone --depth 1 https://github.com/cisco/openh264 -b v2.1.0`. In my experiments, the sum of the zip + unpacked source is equivalent to disk size of a shallow repository (including the `.git` directory).

The advantage of `git clone` is that you can still use the existing logic of selective `git checkout` to restore some code patched for specific configurations (e.g. 
[android-openh264.sh](https://github.com/tanersener/mobile-ffmpeg/blob/development/build/android-openh264.sh#L61)).

If you use a zip package, you must change this technique. I would suggest to unconditionally reset each library directory after successful install to `/prebuilt`. This way, you never need to run custom cleanup during multi-platform and multi-ABI build (no more `make clean`, `git checkout`, etc.). But this same full cleanup can work for `git clone`.

The main limitation of `git clone` is that it doesn't work on arbitrary commit hash (archive…zip does). To resolve this limitation, you may need to use your own fork of each (sub)-repo, and set up a tag there. A possible advantage is that you can set up the tag to fit the `mobile-ffmpeg` release, and you don't need to hardcode the commit hashes in the download script anymore. At any rate, I think that working with forks is necessary, otherwise any upstream repo may be moved or removed.

But you mentioned some **manual steps**. Could you please give an example?

**Comment by tanersener** [comment]
I was deleting the `.git` directory [here](https://github.com/tanersener/mobile-ffmpeg/blob/development/build/arch-common.sh#L204) to free space. But I missed that I need the `.git` directory to revert patched code. `android.sh` is already printing some warnings for `openh264` on `development` branch. Apparently, I'll have to delete that step.

I have to think carefully before creating forks of external libraries. Creating forks alone won't solve the problem. I'll need to manage the tags for them too. The complexity of the project will also increase.

**Comment by alexcohn** [comment]
I believe that maintaining the forks and tagging appropriate commits as e.g. `mobile-ffmpeg.v4.3.2` should be no harder than to keep *'local'* copies of all these libraries inside https://github.com/tanersener/mobile-ffmpeg.git, or maintain the correct git hashes for all these libraries with zip packages approach. Note that zip packages don't resolve the *discontinued repo* concern which is addressed by creating forks.

**Comment by tanersener** [comment]
Thanks for working on this issue. Your findings show that implementing this feature won't improve the current approach. So, making this change doesn't make sense anymore.

Your other advice about creating forks of external libraries and tagging them doesn't look bad. I think it is possible. Just need some time to test them for `cpu-features`, `expat` and `open-h264`.

**Comment by alexcohn** [comment]
Yes, I recently encountered a problem with another library [tess-two](https://github.com/rmtheis/tess-two) repo that has been archived. Sometimes the maintainer can move or hide the repo. Your fork remains the way you set it up.
