### ISSUE TITLE
 uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-full:4.3.2]

### ISSUE THREAD

**Issue by BeantSingh96** [tanersener/mobile-ffmpeg#487]
I want to make it work on android 21 
but asks me to make 24

**Environment**
 - Platform: Android
 - Version 4.3.2
 - Android Studio version (if applicable)   4.0

Help me to solve this

**Comment by BeantSingh96** [comment]
Just Used LTS with version code

**Comment by usmanrana07** [comment]
What difference did LTS brought other than supporting min sdk version 21? Did it increase app size or limited the ffmpeg functionalities etc?

**Comment by BeantSingh96** [comment]
@usmanrana07 LTS does not support camera 
for camera support minSdk should 24

**Comment by usmanrana07** [comment]
Thanks. Is it the only major difference?

**Comment by BeantSingh96** [comment]
Rest you can read description

**Comment by usmanrana07** [comment]
Found it.

**Comment by iamkdblue** [comment]
@usmanrana07 did you find any solution?

**Comment by AllwinJohnson** [comment]
looking for a solution.. can somebody help! I want my  min SDK to be 21.

**Comment by HBiSoft** [comment]
@AllwinJohnson 
Build with LTS enabled, this will allow you to run the library on 16>.  
Then set your `minSdkVersion 21` in your manifest.

If you want camera support, you will have to build the full version.
Since this is only available on sdk 24> and you want your minSdkVersion to be 21, you will have to check programmatically if the device is running 24>. If not, let the user know that the feature is not available on their device.
