### ISSUE TITLE
No method to observe command progress,success or failure

### ISSUE THREAD

**Issue by usmanrana07** [tanersener/mobile-ffmpeg#489]
**Description**
No method to set interface for getting callbacks of progress,success,failure when we execute a command.

**Expected behavior**
There should be some support for observing the command processing.

**Environment**
 - Platform: Android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v4.3.2]

**Comment by tanersener** [comment]
You can follow the progress using `StatisticsCallback`.

All API calls are synchronous, this means that your thread is blocked until the execution is completed. Can you show me an example from a library or framework where you can set a callback for a synchronous API call? Callback needs to include the same data that synchronous API call returns as.

**Comment by usmanrana07** [comment]
The syntax was almost similar to other FFmpeg libs that were having the callbacks. So, this question popped up in mind.
Thanks for clarity.

**Comment by tanersener** [comment]
I guess those API methods are asynchronous. I can take a look if you share the names of those libraries.

**Comment by usmanrana07** [comment]
https://github.com/bravobit/FFmpeg-Android
https://github.com/WritingMinds/ffmpeg-android-java

1st is fork of the 2nd one. So, we can consider them same.

**Comment by tanersener** [comment]
`execute` API method in those projects is asynchronous. They're using async tasks inside. That's why they have a callback/handler. 

`MobileFFmpeg` Android library has similar async task classes under the [util package](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/app/src/main/java/com/arthenica/mobileffmpeg/util). They are not part of the API but you can use them if you want to run commands asynchronously. In the next `MobileFFmpeg` release, they will be included in the API as part of new async API methods. 

To answer your question about API levels, `MobileFFmpeg` has two release variants. Main releases depends on API Level 24. However the LTS releases depend on API Level 16. So, if you want to use minSdkVersion 21, then install an LTS version.

**Comment by usmanrana07** [comment]
Where can i see the dependency url of LTS version? is LTS backward compatible or it has less features than main release. I mean would it brake functionality in Android 10 or 11 etc?
