### ISSUE TITLE
Follow upstream released versions

### ISSUE THREAD

**Issue by rib** [tanersener/mobile-ffmpeg#596]
**Description**
Hi, this is more of a question - I'm wondering why the mobile-ffmpeg releases don't follow the upstream ffmpeg releases and they instead pull ffmpeg master branch snapshots?

I'm struggling to use mobile-ffmpeg libraries with another project (https://github.com/zmwangx/rust-ffmpeg-sys) which gates some of its features according to the released version of ffmpeg but it's feature checks don't work while mobile-ffmpeg doesn't seem to follow standard releases.

**Expected behavior**
I expected that if I build mobile-ffmpeg 4.2 or 4.3 etc then I would get all the ffmpeg libraries that match the corresponding upstream release.

**Current behavior**
I get a development / master snapshot of ffmpeg

**Comment by rib** [comment]
Just for reference, it seemed to work to simply copy in a snapshot of the upstream 4.3.1 release into mobile-ffmpeg 4.3.1 and then rust-ffmpeg-sys was able to build too. The other benefit here (for my use case) is that I can be sure I'm using the same version of ffmpeg on Android as our project uses on Windows too.

**Comment by tanersener** [comment]
First versions of `mobile-ffmpeg` had been using point `ffmpeg` releases. But since `v3.0` this project uses the `master` branch. There are three issues regarding using point releases.

1. Release dates of `ffmpeg` point releases are not predictable. You don't know when there will be a new `ffmpeg` point release. That's why I decided that I don't want this project to depend on point releases and wait for them. Because, this project has its own features that needs to be maintained. And waiting for point releases makes is difficult to publish fixes for `mobile-ffmpeg`.

2. Point releases are not supported by `ffmpeg` developers. Only master branch is supported. Therefore, I don't see any benefit of publishing & supporting a version which is not supported by them.

3. There are many release branches actively maintained by `ffmpeg`: `4.3.x`, `4.2.x`, `4.1.x`, `4.0.x`, `3.4.x`, etc. On July 2020, `ffmpeg` released almost 7 point releases. Sorry, but I don't have time to publish 7 releases. I can't maintain all these branches as `ffmpeg` does.

I don't want to go back have the same issues again. So, I suggest building your own `mobile-ffmpeg` version by changing the `ffmpeg` source used.
