### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "*==/lib/arm/libmobileffmpeg.so": 0

### ISSUE THREAD

**Issue by DanGdl** [tanersener/mobile-ffmpeg#616]
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "*==/lib/arm/libmobileffmpeg.so": 0

java.lang.Runtime.loadLibrary0 (Runtime.java:1016)
java.lang.System.loadLibrary (System.java:1657)
com.arthenica.mobileffmpeg.Config.<clinit> (Config.java:133)
com.arthenica.mobileffmpeg.Config.nativeFFprobeExecute (Config.java)
com.arthenica.mobileffmpeg.FFprobe.execute (FFprobe.java:55)
com.arthenica.mobileffmpeg.FFprobe.getMediaInformationFromCommandArguments (FFprobe.java:123)
com.arthenica.mobileffmpeg.FFprobe.getMediaInformation (FFprobe.java:86)

happens on Samsung Galaxy J6, Android 8.0.0
lib used:  api 'com.arthenica:mobile-ffmpeg-video:4.4.LTS'

**Comment by tanersener** [comment]
There is an issue about the binaries published on `jcenter()`. The versions published are not up-to-date. 

You can use the following workaround while I'm working on the fix.

- Add the following entries into your `proguard-rules.pro` file.

```
-keep class com.arthenica.mobileffmpeg.Config {
    native <methods>;
    void log(long, int, byte[]);
    void statistics(long, int, float, float, long , int, double, double);
}

-keep class com.arthenica.mobileffmpeg.AbiDetect {
    native <methods>;
}
```

**Comment by DanGdl** [comment]
thanks, I'll try

**Comment by zohaib1sahni** [comment]
I'm getting same error.
please solve it asap.

**Comment by sanketkoladiya** [comment]
I am getting the same error any update on this ?

**Comment by omercn18** [comment]
> There is an issue about the binaries published on `jcenter()`. The versions published are not up-to-date.
> 
> You can use the following workaround while I'm working on the fix.
> 
> * Add the following entries into your `proguard-rules.pro` file.
> 
> ```
> -keep class com.arthenica.mobileffmpeg.Config {
>     native <methods>;
>     void log(long, int, byte[]);
>     void statistics(long, int, float, float, long , int, double, double);
> }
> 
> -keep class com.arthenica.mobileffmpeg.AbiDetect {
>     native <methods>;
> }
> ```

Thank you for the workaround. Please update when it is resolved.

**Comment by tanersener** [comment]
I tried to patch Android packages of `v4.4` and `v4.4.LTS` but it didn't  work. There is a problem on bintray/jfrog/jcenter which prevents us from overwriting them. A bintray (jfrog) ticket was created about this problem. It is open since the beginning of December. I'm waiting for them to fix the issue. It may take time due to Christmas season. Meanwhile these are the options.
- You can use the workaround given in this thread
- Install one of the .aar packages published under the [Github Releases](https://github.com/tanersener/mobile-ffmpeg/releases)

**Comment by tanersener** [comment]
Let me recap why we have this issue and what we've done to fix it.

`4.4` and `4.4.LTS` releases were first published to `jcenter()` on 24-25 July 2020. Unfortunately a few days later a bug was reported, #508, and these two releases were patched on August 3rd. Three months later on October/November, `jfrog`/`bintray` decided to drop those patched versions on `jcenter()` and reverted to the original `4.4` and `4.4.LTS` binaries published on July 25th. 

When I reported them the problem, the only explanation they gave me is that overwriting/patching a release on `jcenter()` is against the policies. They haven't explained why they first allowed the patch and why they dropped it without letting me know three months later. 

A few days ago they announced that `bintray` and `jcenter()` will be shut down on May 1st 2021. So, I decided to use `Maven Central` to distribute Android binaries from now on. 

Today, `4.4` and `4.4.LTS` were re-published on `mavenCentral()`. Please use `mavenCentral()` in your projects, which includes the fix for this issue. I also updated the instructions on README.

  - For versions `4.4` and `4.4.LTS`, add `mavenCentral()` to your `build.gradle` and make sure that it is listed before `jcenter()`
  - For `4.3.2` and older releases, add `jcenter()`

These two versions were re-built today. So, you'll see the following output on `logcat` when they're loaded.

```
Loaded mobile-ffmpeg-full-x86-4.4-lts-20210207.
```

**Comment by romater0** [comment]
> There is an issue about the binaries published on `jcenter()`. The versions published are not up-to-date.
> 
> You can use the following workaround while I'm working on the fix.
> 
> * Add the following entries into your `proguard-rules.pro` file.
> 
> ```
> -keep class com.arthenica.mobileffmpeg.Config {
>     native <methods>;
>     void log(long, int, byte[]);
>     void statistics(long, int, float, float, long , int, double, double);
> }
> 
> -keep class com.arthenica.mobileffmpeg.AbiDetect {
>     native <methods>;
> }
> ```

This helped, thanks alot

**Comment by VivekThummar52** [comment]
> Let me recap why we have this issue and what we've done to fix it.
> 
> `4.4` and `4.4.LTS` releases were first published to `jcenter()` on 24-25 July 2020. Unfortunately a few days later a bug was reported, #508, and these two releases were patched on August 3rd. Three months later on October/November, `jfrog`/`bintray` decided to drop those patched versions on `jcenter()` and reverted to the original `4.4` and `4.4.LTS` binaries published on July 25th.
> 
> When I reported them the problem, the only explanation they gave me is that overwriting/patching a release on `jcenter()` is against the policies. They haven't explained why they first allowed the patch and why they dropped it without letting me know three months later.
> 
> A few days ago they announced that `bintray` and `jcenter()` will be shut down on May 1st 2021. So, I decided to use `Maven Central` to distribute Android binaries from now on.
> 
> Today, `4.4` and `4.4.LTS` were re-published on `mavenCentral()`. Please use `mavenCentral()` in your projects, which includes the fix for this issue. I also updated the instructions on README.
> 
> * For versions `4.4` and `4.4.LTS`, add `mavenCentral()` to your `build.gradle` and make sure that it is listed before `jcenter()`
> * For `4.3.2` and older releases, add `jcenter()`
> 
> These two versions were re-built today. So, you'll see the following output on `logcat` when they're loaded.
> 
> ```
> Loaded mobile-ffmpeg-full-x86-4.4-lts-20210207.
> ```

This solution helped me but not every time, generally most of the time whenever i installs app and fires any command, for the first time app will crash and then after all time it works fine..
